language: node_js
node_js:
    - "11.12.0"

sudo: false

#cache
cache:
  directories:
    - "node_modules"

notifications:
  # 邮件发送部署结果通知
  email:
    recipients:
      - zebrateam@163.com
    on_success: change
    on_failure: always

# S: Build Lifecycle
before_install:
  - sudo apt-get install libnotify-bin

install:
  - npm install
#  - gem install travis
#  - travis login --pro --github-token ${GH_TOKEN}

before_script:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g
  - chmod +x _travis.sh

script:
  - hexo clean && hexo g

after_success:
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

after_script:
  - ./_travis.sh

# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/zebra-team/zebra-team.github.io.git
