# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:
- page: 分享专栏
  url: /categories/分享专栏/
  icon:
- page: 解决方案
  url: /categories/解决方案/
  icon:
- page: 时间轴
  url: /archives/
  icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: './img/head-bg.png'
  url: 'https://www.yuque.com/zebratalk'

display_updated: true

# 各个小工具的设置

## widgets
widgets:
#  - search
  - notification
  - friends
  - tagcloud
#  - social
  - category
  - archive

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <p>
                Zebra分享：<a href="https://www.yuque.com/books/share/0da60d37-21df-4bef-8cea-e5322d0bb74f?#" title="fork me" target="_blank">Zebra前端分享专栏</a> <br/>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/zebra-share-team
 - name: 邮箱
   icon: envelope-o
   href: mailto:zebrateam@163.com

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: true
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - 语雀: https://www.yuque.com/zebratalk
  - 掘金社区: https://juejin.im/user/5e64b845e51d45272443f328
  - 知乎: https://www.zhihu.com/people/zebra.team
  - 微博: https://weibo.com/p/1005051651050117/home
  - 哔哩哔哩: https://space.bilibili.com/522838749


# 主题自定义个性化配置

## 网站宣传语
branding: 分享是件简单有趣的事情

## 设置banner背景图片
banner:
    img: ./img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="" target="_blank">Zebra</a>

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## Valine评论
valine:
   enable: true
   appId: 0q0vid2kizGymmd0dNKs3lOY-gzGzoHsz
   appKey: wNj5sJAu5hReOirB3QbKqNiA
   placeholder: 说点什么吧
   notify: false
   verify: true
   avatar: mm
   meta: nick,mail
   pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
   enable: false
   clientID:
   clientSecret:
   repo:
   owner:
   admin:
   perPage:
   distractionFreeMode: true

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

## 网站访客统计
visit_counter:
   site: false
   page: false

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2020
beian: 
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.0.0
